// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file tribune/profile/v1/corpus_internal.proto (package tribune.profile.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CorpusDoc } from "../../types/v1/types_pb";
import { file_tribune_types_v1_types } from "../../types/v1/types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tribune/profile/v1/corpus_internal.proto.
 */
export const file_tribune_profile_v1_corpus_internal: GenFile = /*@__PURE__*/
  fileDesc("Cih0cmlidW5lL3Byb2ZpbGUvdjEvY29ycHVzX2ludGVybmFsLnByb3RvEhJ0cmlidW5lLnByb2ZpbGUudjEiMwoeR2V0VGVuYW50Q29ycHVzSW50ZXJuYWxSZXF1ZXN0EhEKCXRlbmFudF9pZBgBIAEoCSJOCh9HZXRUZW5hbnRDb3JwdXNJbnRlcm5hbFJlc3BvbnNlEisKBmNvcnB1cxgBIAEoCzIbLnRyaWJ1bmUudHlwZXMudjEuQ29ycHVzRG9jMpwBChVDb3JwdXNJbnRlcm5hbFNlcnZpY2USggEKF0dldFRlbmFudENvcnB1c0ludGVybmFsEjIudHJpYnVuZS5wcm9maWxlLnYxLkdldFRlbmFudENvcnB1c0ludGVybmFsUmVxdWVzdBozLnRyaWJ1bmUucHJvZmlsZS52MS5HZXRUZW5hbnRDb3JwdXNJbnRlcm5hbFJlc3BvbnNlQlJaUGdpdGh1Yi5jb20vcmFyZWNpcmNsZXMvdHJpYnVuZS1iYWNrZW5kL3Byb3RvL2dlbi9nby90cmlidW5lL3Byb2ZpbGUvdjE7cGJwcm9maWxlYgZwcm90bzM", [file_tribune_types_v1_types]);

/**
 * @generated from message tribune.profile.v1.GetTenantCorpusInternalRequest
 */
export type GetTenantCorpusInternalRequest = Message<"tribune.profile.v1.GetTenantCorpusInternalRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;
};

/**
 * Describes the message tribune.profile.v1.GetTenantCorpusInternalRequest.
 * Use `create(GetTenantCorpusInternalRequestSchema)` to create a new message.
 */
export const GetTenantCorpusInternalRequestSchema: GenMessage<GetTenantCorpusInternalRequest> = /*@__PURE__*/
  messageDesc(file_tribune_profile_v1_corpus_internal, 0);

/**
 * @generated from message tribune.profile.v1.GetTenantCorpusInternalResponse
 */
export type GetTenantCorpusInternalResponse = Message<"tribune.profile.v1.GetTenantCorpusInternalResponse"> & {
  /**
   * @generated from field: tribune.types.v1.CorpusDoc corpus = 1;
   */
  corpus?: CorpusDoc;
};

/**
 * Describes the message tribune.profile.v1.GetTenantCorpusInternalResponse.
 * Use `create(GetTenantCorpusInternalResponseSchema)` to create a new message.
 */
export const GetTenantCorpusInternalResponseSchema: GenMessage<GetTenantCorpusInternalResponse> = /*@__PURE__*/
  messageDesc(file_tribune_profile_v1_corpus_internal, 1);

/**
 * @generated from service tribune.profile.v1.CorpusInternalService
 */
export const CorpusInternalService: GenService<{
  /**
   * @generated from rpc tribune.profile.v1.CorpusInternalService.GetTenantCorpusInternal
   */
  getTenantCorpusInternal: {
    methodKind: "unary";
    input: typeof GetTenantCorpusInternalRequestSchema;
    output: typeof GetTenantCorpusInternalResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tribune_profile_v1_corpus_internal, 0);

