// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file tribune/search/v1/search.proto (package tribune.search.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Conversation } from "../../conversation/v1/conversation_pb";
import { file_tribune_conversation_v1_conversation } from "../../conversation/v1/conversation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tribune/search/v1/search.proto.
 */
export const file_tribune_search_v1_search: GenFile = /*@__PURE__*/
  fileDesc("Ch50cmlidW5lL3NlYXJjaC92MS9zZWFyY2gucHJvdG8SEXRyaWJ1bmUuc2VhcmNoLnYxIlIKGlNlYXJjaENvbnZlcnNhdGlvbnNSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEhEKCXBhZ2Vfc2l6ZRgCIAEoBRISCgpwYWdlX3Rva2VuGAMgASgJIlsKG1NlYXJjaENvbnZlcnNhdGlvbnNSZXNwb25zZRI8Cg1jb252ZXJzYXRpb25zGAEgAygLMiUudHJpYnVuZS5jb252ZXJzYXRpb24udjEuQ29udmVyc2F0aW9uMoUBCg1TZWFyY2hTZXJ2aWNlEnQKE1NlYXJjaENvbnZlcnNhdGlvbnMSLS50cmlidW5lLnNlYXJjaC52MS5TZWFyY2hDb252ZXJzYXRpb25zUmVxdWVzdBouLnRyaWJ1bmUuc2VhcmNoLnYxLlNlYXJjaENvbnZlcnNhdGlvbnNSZXNwb25zZUJQWk5naXRodWIuY29tL3JhcmVjaXJjbGVzL3RyaWJ1bmUtYmFja2VuZC9wcm90by9nZW4vZ28vdHJpYnVuZS9zZWFyY2gvdjE7cGJzZWFyY2hiBnByb3RvMw", [file_tribune_conversation_v1_conversation]);

/**
 * @generated from message tribune.search.v1.SearchConversationsRequest
 */
export type SearchConversationsRequest = Message<"tribune.search.v1.SearchConversationsRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 3;
   */
  pageToken: string;
};

/**
 * Describes the message tribune.search.v1.SearchConversationsRequest.
 * Use `create(SearchConversationsRequestSchema)` to create a new message.
 */
export const SearchConversationsRequestSchema: GenMessage<SearchConversationsRequest> = /*@__PURE__*/
  messageDesc(file_tribune_search_v1_search, 0);

/**
 * @generated from message tribune.search.v1.SearchConversationsResponse
 */
export type SearchConversationsResponse = Message<"tribune.search.v1.SearchConversationsResponse"> & {
  /**
   * @generated from field: repeated tribune.conversation.v1.Conversation conversations = 1;
   */
  conversations: Conversation[];
};

/**
 * Describes the message tribune.search.v1.SearchConversationsResponse.
 * Use `create(SearchConversationsResponseSchema)` to create a new message.
 */
export const SearchConversationsResponseSchema: GenMessage<SearchConversationsResponse> = /*@__PURE__*/
  messageDesc(file_tribune_search_v1_search, 1);

/**
 * @generated from service tribune.search.v1.SearchService
 */
export const SearchService: GenService<{
  /**
   * SearchConversations searches for conversations based on a query string matching
   * contacts name, email and phone number.
   *
   * @generated from rpc tribune.search.v1.SearchService.SearchConversations
   */
  searchConversations: {
    methodKind: "unary";
    input: typeof SearchConversationsRequestSchema;
    output: typeof SearchConversationsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tribune_search_v1_search, 0);

