// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file tribune/form/v1/form_internal.proto (package tribune.form.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Form, FormSchema } from "./form_pb";
import { file_tribune_form_v1_form } from "./form_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tribune/form/v1/form_internal.proto.
 */
export const file_tribune_form_v1_form_internal: GenFile = /*@__PURE__*/
  fileDesc("CiN0cmlidW5lL2Zvcm0vdjEvZm9ybV9pbnRlcm5hbC5wcm90bxIPdHJpYnVuZS5mb3JtLnYxIqMBChhMaXN0Rm9ybXNJbnRlcm5hbFJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJEkUKBmZpbHRlchgCIAMoCzI1LnRyaWJ1bmUuZm9ybS52MS5MaXN0Rm9ybXNJbnRlcm5hbFJlcXVlc3QuRmlsdGVyRW50cnkaLQoLRmlsdGVyRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJBChlMaXN0Rm9ybXNJbnRlcm5hbFJlc3BvbnNlEiQKBWZvcm1zGAEgAygLMhUudHJpYnVuZS5mb3JtLnYxLkZvcm0iMgodR2V0UHJpbWFyeUZvcm1JbnRlcm5hbFJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJIkUKHkdldFByaW1hcnlGb3JtSW50ZXJuYWxSZXNwb25zZRIjCgRmb3JtGAEgASgLMhUudHJpYnVuZS5mb3JtLnYxLkZvcm0iNQogQ3JlYXRlUHJpbWFyeUZvcm1JbnRlcm5hbFJlcXVlc3QSEQoJdGVuYW50X2lkGAEgASgJInUKIUNyZWF0ZVByaW1hcnlGb3JtSW50ZXJuYWxSZXNwb25zZRIjCgRmb3JtGAEgASgLMhUudHJpYnVuZS5mb3JtLnYxLkZvcm0SKwoGc2NoZW1hGAIgASgLMhsudHJpYnVuZS5mb3JtLnYxLkZvcm1TY2hlbWEygQMKE0Zvcm1JbnRlcm5hbFNlcnZpY2USagoRTGlzdEZvcm1zSW50ZXJuYWwSKS50cmlidW5lLmZvcm0udjEuTGlzdEZvcm1zSW50ZXJuYWxSZXF1ZXN0GioudHJpYnVuZS5mb3JtLnYxLkxpc3RGb3Jtc0ludGVybmFsUmVzcG9uc2USeQoWR2V0UHJpbWFyeUZvcm1JbnRlcm5hbBIuLnRyaWJ1bmUuZm9ybS52MS5HZXRQcmltYXJ5Rm9ybUludGVybmFsUmVxdWVzdBovLnRyaWJ1bmUuZm9ybS52MS5HZXRQcmltYXJ5Rm9ybUludGVybmFsUmVzcG9uc2USggEKGUNyZWF0ZVByaW1hcnlGb3JtSW50ZXJuYWwSMS50cmlidW5lLmZvcm0udjEuQ3JlYXRlUHJpbWFyeUZvcm1JbnRlcm5hbFJlcXVlc3QaMi50cmlidW5lLmZvcm0udjEuQ3JlYXRlUHJpbWFyeUZvcm1JbnRlcm5hbFJlc3BvbnNlQkxaSmdpdGh1Yi5jb20vcmFyZWNpcmNsZXMvdHJpYnVuZS1iYWNrZW5kL3Byb3RvL2dlbi9nby90cmlidW5lL2Zvcm0vdjE7cGJmb3JtYgZwcm90bzM", [file_tribune_form_v1_form]);

/**
 * @generated from message tribune.form.v1.ListFormsInternalRequest
 */
export type ListFormsInternalRequest = Message<"tribune.form.v1.ListFormsInternalRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;

  /**
   * @generated from field: map<string, string> filter = 2;
   */
  filter: { [key: string]: string };
};

/**
 * Describes the message tribune.form.v1.ListFormsInternalRequest.
 * Use `create(ListFormsInternalRequestSchema)` to create a new message.
 */
export const ListFormsInternalRequestSchema: GenMessage<ListFormsInternalRequest> = /*@__PURE__*/
  messageDesc(file_tribune_form_v1_form_internal, 0);

/**
 * @generated from message tribune.form.v1.ListFormsInternalResponse
 */
export type ListFormsInternalResponse = Message<"tribune.form.v1.ListFormsInternalResponse"> & {
  /**
   * @generated from field: repeated tribune.form.v1.Form forms = 1;
   */
  forms: Form[];
};

/**
 * Describes the message tribune.form.v1.ListFormsInternalResponse.
 * Use `create(ListFormsInternalResponseSchema)` to create a new message.
 */
export const ListFormsInternalResponseSchema: GenMessage<ListFormsInternalResponse> = /*@__PURE__*/
  messageDesc(file_tribune_form_v1_form_internal, 1);

/**
 * @generated from message tribune.form.v1.GetPrimaryFormInternalRequest
 */
export type GetPrimaryFormInternalRequest = Message<"tribune.form.v1.GetPrimaryFormInternalRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;
};

/**
 * Describes the message tribune.form.v1.GetPrimaryFormInternalRequest.
 * Use `create(GetPrimaryFormInternalRequestSchema)` to create a new message.
 */
export const GetPrimaryFormInternalRequestSchema: GenMessage<GetPrimaryFormInternalRequest> = /*@__PURE__*/
  messageDesc(file_tribune_form_v1_form_internal, 2);

/**
 * @generated from message tribune.form.v1.GetPrimaryFormInternalResponse
 */
export type GetPrimaryFormInternalResponse = Message<"tribune.form.v1.GetPrimaryFormInternalResponse"> & {
  /**
   * @generated from field: tribune.form.v1.Form form = 1;
   */
  form?: Form;
};

/**
 * Describes the message tribune.form.v1.GetPrimaryFormInternalResponse.
 * Use `create(GetPrimaryFormInternalResponseSchema)` to create a new message.
 */
export const GetPrimaryFormInternalResponseSchema: GenMessage<GetPrimaryFormInternalResponse> = /*@__PURE__*/
  messageDesc(file_tribune_form_v1_form_internal, 3);

/**
 * @generated from message tribune.form.v1.CreatePrimaryFormInternalRequest
 */
export type CreatePrimaryFormInternalRequest = Message<"tribune.form.v1.CreatePrimaryFormInternalRequest"> & {
  /**
   * @generated from field: string tenant_id = 1;
   */
  tenantId: string;
};

/**
 * Describes the message tribune.form.v1.CreatePrimaryFormInternalRequest.
 * Use `create(CreatePrimaryFormInternalRequestSchema)` to create a new message.
 */
export const CreatePrimaryFormInternalRequestSchema: GenMessage<CreatePrimaryFormInternalRequest> = /*@__PURE__*/
  messageDesc(file_tribune_form_v1_form_internal, 4);

/**
 * @generated from message tribune.form.v1.CreatePrimaryFormInternalResponse
 */
export type CreatePrimaryFormInternalResponse = Message<"tribune.form.v1.CreatePrimaryFormInternalResponse"> & {
  /**
   * @generated from field: tribune.form.v1.Form form = 1;
   */
  form?: Form;

  /**
   * @generated from field: tribune.form.v1.FormSchema schema = 2;
   */
  schema?: FormSchema;
};

/**
 * Describes the message tribune.form.v1.CreatePrimaryFormInternalResponse.
 * Use `create(CreatePrimaryFormInternalResponseSchema)` to create a new message.
 */
export const CreatePrimaryFormInternalResponseSchema: GenMessage<CreatePrimaryFormInternalResponse> = /*@__PURE__*/
  messageDesc(file_tribune_form_v1_form_internal, 5);

/**
 * @generated from service tribune.form.v1.FormInternalService
 */
export const FormInternalService: GenService<{
  /**
   * @generated from rpc tribune.form.v1.FormInternalService.ListFormsInternal
   */
  listFormsInternal: {
    methodKind: "unary";
    input: typeof ListFormsInternalRequestSchema;
    output: typeof ListFormsInternalResponseSchema;
  },
  /**
   * @generated from rpc tribune.form.v1.FormInternalService.GetPrimaryFormInternal
   */
  getPrimaryFormInternal: {
    methodKind: "unary";
    input: typeof GetPrimaryFormInternalRequestSchema;
    output: typeof GetPrimaryFormInternalResponseSchema;
  },
  /**
   * @generated from rpc tribune.form.v1.FormInternalService.CreatePrimaryFormInternal
   */
  createPrimaryFormInternal: {
    methodKind: "unary";
    input: typeof CreatePrimaryFormInternalRequestSchema;
    output: typeof CreatePrimaryFormInternalResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tribune_form_v1_form_internal, 0);

