// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file tribune/event/v1/services.proto (package tribune.event.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file tribune/event/v1/services.proto.
 */
export const file_tribune_event_v1_services: GenFile = /*@__PURE__*/
  fileDesc("Ch90cmlidW5lL2V2ZW50L3YxL3NlcnZpY2VzLnByb3RvEhB0cmlidW5lLmV2ZW50LnYxKu4CCgtTZXJ2aWNlTmFtZRIcChhTRVJWSUNFX05BTUVfVU5TUEVDSUZJRUQQABIbChdTRVJWSUNFX05BTUVfT05CT0FSRElORxABEhgKFFNFUlZJQ0VfTkFNRV9DT05UQUNUEAISHQoZU0VSVklDRV9OQU1FX0NPTlZFUlNBVElPThADEhgKFFNFUlZJQ0VfTkFNRV9QUk9GSUxFEAQSGgoWU0VSVklDRV9OQU1FX01FU1NBR0lORxAFEhUKEVNFUlZJQ0VfTkFNRV9GT1JNEAYSGQoVU0VSVklDRV9OQU1FX01FVEFDSEFUEAcSFgoSU0VSVklDRV9OQU1FX0VNQUlMEAgSHQoZU0VSVklDRV9OQU1FX05PVElGSUNBVElPThAJEhoKFlNFUlZJQ0VfTkFNRV9USUNLRVRJTkcQChIXChNTRVJWSUNFX05BTUVfU0VBUkNIEAsSFwoTU0VSVklDRV9OQU1FX0VWRU5UUxAMQk5aTGdpdGh1Yi5jb20vcmFyZWNpcmNsZXMvdHJpYnVuZS1iYWNrZW5kL3Byb3RvL2dlbi9nby90cmlidW5lL2V2ZW50L3YxO3BiZXZlbnRiBnByb3RvMw");

/**
 * @generated from enum tribune.event.v1.ServiceName
 */
export enum ServiceName {
  /**
   * @generated from enum value: SERVICE_NAME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SERVICE_NAME_ONBOARDING = 1;
   */
  ONBOARDING = 1,

  /**
   * @generated from enum value: SERVICE_NAME_CONTACT = 2;
   */
  CONTACT = 2,

  /**
   * @generated from enum value: SERVICE_NAME_CONVERSATION = 3;
   */
  CONVERSATION = 3,

  /**
   * @generated from enum value: SERVICE_NAME_PROFILE = 4;
   */
  PROFILE = 4,

  /**
   * @generated from enum value: SERVICE_NAME_MESSAGING = 5;
   */
  MESSAGING = 5,

  /**
   * @generated from enum value: SERVICE_NAME_FORM = 6;
   */
  FORM = 6,

  /**
   * @generated from enum value: SERVICE_NAME_METACHAT = 7;
   */
  METACHAT = 7,

  /**
   * @generated from enum value: SERVICE_NAME_EMAIL = 8;
   */
  EMAIL = 8,

  /**
   * @generated from enum value: SERVICE_NAME_NOTIFICATION = 9;
   */
  NOTIFICATION = 9,

  /**
   * @generated from enum value: SERVICE_NAME_TICKETING = 10;
   */
  TICKETING = 10,

  /**
   * @generated from enum value: SERVICE_NAME_SEARCH = 11;
   */
  SEARCH = 11,

  /**
   * @generated from enum value: SERVICE_NAME_EVENTS = 12;
   */
  EVENTS = 12,
}

/**
 * Describes the enum tribune.event.v1.ServiceName.
 */
export const ServiceNameSchema: GenEnum<ServiceName> = /*@__PURE__*/
  enumDesc(file_tribune_event_v1_services, 0);

